services:
  - type: web
    plan: free
    name: pyUltroid
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn app:app & python3 -m pyUltroid
    repo: https://github.com/rick1128/test      
    branch: main
    envVars:
      - key: TG_BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: APP_HASH
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_URL
        sync: false    
    autoDeploy: false
